daemonize: false
pidfile: /var/run/pmacct/nfacctd.pid
collector_port: 9995
plugins: prometheus
prometheus_output: standard
prometheus_port: 9101
aggregate: src_host, dst_host, src_port, dst_port, proto, in_iface
