frr version 8.4.1
hostname wan5G
log syslog informational

interface lo
 ip address 100.64.3.1/32
!
interface eth1
 description eBGP-to-NodeA-5G
 ip address 192.168.3.1/30
!
router bgp 65003
 bgp router-id 100.64.3.1
 no bgp network import-check
 neighbor 192.168.3.2 remote-as 65000
 !
 address-family ipv4 unicast
  network 203.0.113.0/24
  neighbor 192.168.3.2 route-map PERMIT-ALL in
  neighbor 192.168.3.2 route-map PERMIT-ALL out
  neighbor 192.168.3.2 next-hop-self
 exit-address-family
!
route-map PERMIT-ALL permit 10
!
ip route 203.0.113.0/24 Null0
