frr version 8.4.1
hostname nodeD
log syslog informational

interface lo
 ip address 4.4.4.4/32
!
interface eth1
 description Radio-to-NodeB
 ip address 10.4.0.2/30
 ip ospf hello-interval 1
 ip ospf dead-interval 4
 ip ospf bfd
 ip ospf cost 390
!
interface eth2
 description 5G-to-NodeC
 ip address 10.5.0.2/30
 ip ospf hello-interval 1
 ip ospf dead-interval 4
 ip ospf bfd
 ip ospf cost 2
!
interface eth3
 description Radio-to-NodeE
 ip address 10.6.0.1/30
 ip ospf hello-interval 1
 ip ospf dead-interval 4
 ip ospf bfd
 ip ospf cost 390
!
router ospf
 ospf router-id 4.4.4.4
 auto-cost reference-bandwidth 100000
 timers throttle spf 50 100 5000
 network 4.4.4.4/32 area 0
 network 10.4.0.0/30 area 0
 network 10.5.0.0/30 area 0
 network 10.6.0.0/30 area 0
!
bfd
 peer 10.4.0.1
  receive-interval 50
  transmit-interval 50
 !
 peer 10.5.0.1
  receive-interval 50
  transmit-interval 50
 !
 peer 10.6.0.2
  receive-interval 50
  transmit-interval 50
 !
