daemonize: false
pidfile: /tmp/nfacctd.pid
nfacctd_port: 9995
nfacctd_ip: 0.0.0.0
plugins: print[json_out]
print_output: json
print_output_file: /tmp/flows.json
print_refresh_time: 30
aggregate: src_host, dst_host, src_port, dst_port, proto, in_iface
