frr version 8.4.1
hostname nodeB
log syslog informational

interface lo
 ip address 2.2.2.2/32
!
interface eth1
 description 5G-to-NodeA
 ip address 10.1.0.2/30
 ip ospf hello-interval 1
 ip ospf dead-interval 4
 ip ospf bfd
 ip ospf cost 2
!
interface eth2
 description Radio-to-NodeD
 ip address 10.4.0.1/30
 ip ospf hello-interval 1
 ip ospf dead-interval 4
 ip ospf bfd
 ip ospf cost 390
!
router ospf
 ospf router-id 2.2.2.2
 auto-cost reference-bandwidth 100000
 timers throttle spf 50 100 5000
 network 2.2.2.2/32 area 0
 network 10.1.0.0/30 area 0
 network 10.4.0.0/30 area 0
!
bfd
 peer 10.1.0.1
  receive-interval 50
  transmit-interval 50
 !
 peer 10.4.0.2
  receive-interval 50
  transmit-interval 50
 !
