frr version 8.4.1
hostname nodeC
log syslog informational

interface lo
 ip address 3.3.3.3/32
!
interface eth1
 description SATCOM-to-NodeA
 ip address 10.2.0.2/30
 ip ospf hello-interval 1
 ip ospf dead-interval 4
 ip ospf bfd
 ip ospf cost 100
!
interface eth2
 description 5G-to-NodeD
 ip address 10.5.0.1/30
 ip ospf hello-interval 1
 ip ospf dead-interval 4
 ip ospf bfd
 ip ospf cost 2
!
router ospf
 ospf router-id 3.3.3.3
 auto-cost reference-bandwidth 100000
 timers throttle spf 50 100 5000
 network 3.3.3.3/32 area 0
 network 10.2.0.0/30 area 0
 network 10.5.0.0/30 area 0
!
bfd
 peer 10.2.0.1
  receive-interval 50
  transmit-interval 50
 !
 peer 10.5.0.2
  receive-interval 50
  transmit-interval 50
 !
