frr version 8.4.1
hostname nodeA
log syslog informational

interface lo
 ip address 1.1.1.1/32
!
interface eth1
 description 5G-to-NodeB
 ip address 10.1.0.1/30
 ip ospf hello-interval 1
 ip ospf dead-interval 4
 ip ospf bfd
 ip ospf cost 2
!
interface eth2
 description SATCOM-to-NodeC
 ip address 10.2.0.1/30
 ip ospf hello-interval 1
 ip ospf dead-interval 4
 ip ospf bfd
 ip ospf cost 100
!
interface eth3
 description Radio-to-NodeE
 ip address 10.3.0.1/30
 ip ospf hello-interval 1
 ip ospf dead-interval 4
 ip ospf bfd
 ip ospf cost 390
!
interface eth4
 description WAN-SATCOM-uplink
 ip address 192.168.1.2/30
!
interface eth5
 description WAN-Radio-uplink
 ip address 192.168.2.2/30
!
interface eth6
 description WAN-5G-uplink
 ip address 192.168.3.2/30
!
router ospf
 ospf router-id 1.1.1.1
 auto-cost reference-bandwidth 100000
 timers throttle spf 50 100 5000
 network 1.1.1.1/32 area 0
 network 10.1.0.0/30 area 0
 network 10.2.0.0/30 area 0
 network 10.3.0.0/30 area 0
 redistribute bgp route-map FROM-BGP
!
router bgp 65000
 bgp router-id 1.1.1.1
 neighbor 192.168.1.1 remote-as 65001
 neighbor 192.168.2.1 remote-as 65002
 neighbor 192.168.3.1 remote-as 65003
 !
 address-family ipv4 unicast
  neighbor 192.168.1.1 route-map SET-PREF-SATCOM in
  neighbor 192.168.1.1 route-map PERMIT-ALL out
  neighbor 192.168.2.1 route-map SET-PREF-RADIO in
  neighbor 192.168.2.1 route-map PERMIT-ALL out
  neighbor 192.168.3.1 route-map SET-PREF-5G in
  neighbor 192.168.3.1 route-map PERMIT-ALL out
  redistribute ospf route-map FROM-OSPF
 exit-address-family
!
route-map FROM-OSPF permit 10
 match tag 100
 on-match goto 20
route-map FROM-OSPF deny 15
 match tag 200
route-map FROM-OSPF permit 20
 set tag 200
!
route-map FROM-BGP deny 5
 match tag 200
route-map FROM-BGP permit 10
 set tag 100
!
route-map PERMIT-ALL permit 10
!
route-map SET-PREF-5G permit 10
 set local-preference 300
!
route-map SET-PREF-RADIO permit 10
 set local-preference 200
!
route-map SET-PREF-SATCOM permit 10
 set local-preference 100
!
bfd
 peer 10.1.0.2
  receive-interval 50
  transmit-interval 50
 !
 peer 10.2.0.2
  receive-interval 50
  transmit-interval 50
 !
 peer 10.3.0.2
  receive-interval 50
  transmit-interval 50
 !
